### ISSUE TITLE
Outdated installation instructions

### ISSUE THREAD

**Issue by sixtyfive** [adafruit/Adafruit_CircuitPython_FancyLED#22]
[README.rst](README.rst) instructs:

> Please ensure all dependencies are available on the CircuitPython filesystem. This is easily achieved by downloading the Adafruit library and driver bundle.

From what I understand, it should instead be pointing towards https://learn.adafruit.com/fancyled-library-for-circuitpython/install-software?

**Comment by evaherrada** [comment]
Not really. That link just gives you the more or less the same instructions.

**Comment by evaherrada** [comment]
I'm closing this, but if you feel that further discussion is warranted, just leave another message and I can reopen it.

**Comment by sixtyfive** [comment]
I was asked to open this Issue on the Adafruit discord by someone I think works for Adafruit. What I _can_ say is that from a user's perspective, it'd have been nice if there was an additional phrase like "after downloading the bundle, copy folder so and so to the lib folder on your device".

**Comment by dhalbert** [comment]
I was the one who talked with @sixtyfive on discord. I agree that the boilerplate is somewhat unclear. @sixtyfive remembers the time when one could fit the whole bundle on CIRCUITPY, and assumed that's what it was saying. I think the boilerplate for this and other libraries could be changed to either mention the specific dependencies (like `neopixel` in this case), or changing the text to something like:

>Please ensure all dependencies are available on the CircuitPython filesystem. This is easily achieved by downloading the Adafruit library and driver bundle, _and copying the required libraries to the `CIRCUITPY/lib` folder._
